apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - policies/require-digest.yaml
  - policies/disallow-latest-tag.yaml
  - policies/require-non-root.yaml
  - policies/require-signed-images.yaml
  - policies/require-sbom-attestation.yaml
