apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sauravrana646/portfolio-cloud-platform.git
    targetRevision: main
    path: argocd/appsets/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
