replicaCount: 2
podDisruptionBudget:
  enabled: true
  minAvailable: 1
networkPolicy:
  enabled: true
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
kyvernoEnforce: true
