apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-uat
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    - repoURL: https://github.com/sauravrana646/portfolio-cloud-platform.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/sauravrana646/portfolio-cloud-platform.git
      targetRevision: main
      path: charts/demo-app
      helm:
        valueFiles:
          - values-staging.yaml
          - $values/deploy/environments/uat/images.yaml
          - $values/deploy/environments/uat/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
