apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/sauravrana646/portfolio-cloud-platform.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/sauravrana646/portfolio-cloud-platform.git
      targetRevision: main
      path: charts/bootstrap-layer/kyverno
      helm:
        releaseName: kyverno
        valueFiles:
          - $values/helm-values/bootstrap-layer/kyverno/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
