apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-infisical-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/sauravrana646/portfolio-cloud-platform.git
      targetRevision: main
      ref: values
    - repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
      chart: secrets-operator
      targetRevision: 0.11.7
      helm:
        releaseName: infisical-secrets-operator
        valueFiles:
          - $values/deploy/platform/infisical-operator-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
