apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-infisical-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/sauravrana646/portfolio-cloud-platform.git
    targetRevision: main
    path: charts/bootstrap-layer/infisical-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
